# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 406)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layout_v = QtWidgets.QVBoxLayout()
        self.layout_v.setObjectName("layout_v")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b_save = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_save.sizePolicy().hasHeightForWidth())
        self.b_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_save.setFont(font)
        self.b_save.setObjectName("b_save")
        self.horizontalLayout_2.addWidget(self.b_save)
        self.l_save = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_save.setFont(font)
        self.l_save.setToolTip("")
        self.l_save.setText("")
        self.l_save.setObjectName("l_save")
        self.horizontalLayout_2.addWidget(self.l_save)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_vid = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_vid.sizePolicy().hasHeightForWidth())
        self.b_vid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_vid.setFont(font)
        self.b_vid.setObjectName("b_vid")
        self.horizontalLayout.addWidget(self.b_vid)
        self.l_vid = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_vid.setFont(font)
        self.l_vid.setText("")
        self.l_vid.setObjectName("l_vid")
        self.horizontalLayout.addWidget(self.l_vid)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.b_colour = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_colour.sizePolicy().hasHeightForWidth())
        self.b_colour.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_colour.setFont(font)
        self.b_colour.setObjectName("b_colour")
        self.horizontalLayout_5.addWidget(self.b_colour)
        self.l_colour = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_colour.setFont(font)
        self.l_colour.setText("")
        self.l_colour.setObjectName("l_colour")
        self.horizontalLayout_5.addWidget(self.l_colour)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.t_fps = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.t_fps.setFont(font)
        self.t_fps.setAlignment(QtCore.Qt.AlignCenter)
        self.t_fps.setObjectName("t_fps")
        self.horizontalLayout_3.addWidget(self.t_fps)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c_of = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_of.setFont(font)
        self.c_of.setObjectName("c_of")
        self.verticalLayout_3.addWidget(self.c_of)
        self.c_back_of = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_back_of.setFont(font)
        self.c_back_of.setObjectName("c_back_of")
        self.verticalLayout_3.addWidget(self.c_back_of)
        self.c_depth = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_depth.setFont(font)
        self.c_depth.setObjectName("c_depth")
        self.verticalLayout_3.addWidget(self.c_depth)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_6 = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_4.addWidget(self.checkBox_6)
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_4.addWidget(self.checkBox_5)
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_4.addWidget(self.checkBox_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.layout_v.addLayout(self.horizontalLayout_7)
        self.b_run = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_run.sizePolicy().hasHeightForWidth())
        self.b_run.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_run.setFont(font)
        self.b_run.setObjectName("b_run")
        self.layout_v.addWidget(self.b_run)
        self.verticalLayout_7.addLayout(self.layout_v)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.b_save.setToolTip(_translate("Dialog", "Save path for results"))
        self.b_save.setText(_translate("Dialog", "Save Path"))
        self.b_vid.setToolTip(_translate("Dialog", "Video you wish to analyse"))
        self.b_vid.setText(_translate("Dialog", "Open Video"))
        self.b_colour.setToolTip(_translate("Dialog", "Filling colour around the video"))
        self.b_colour.setText(_translate("Dialog", "Image Fill Colour"))
        self.label.setToolTip(_translate("Dialog", "Select the videos you wish to create"))
        self.label.setText(_translate("Dialog", "Create Video"))
        self.label_2.setText(_translate("Dialog", "Fps"))
        self.t_fps.setToolTip(_translate("Dialog", "The fps for the created videos"))
        self.t_fps.setText(_translate("Dialog", "30"))
        self.c_of.setToolTip(_translate("Dialog", "Video of optical flow"))
        self.c_of.setText(_translate("Dialog", "Optical flow"))
        self.c_back_of.setToolTip(_translate("Dialog", "Video of backward optical flow"))
        self.c_back_of.setText(_translate("Dialog", "Back Optical flow"))
        self.c_depth.setToolTip(_translate("Dialog", "Video of depth estimation"))
        self.c_depth.setText(_translate("Dialog", "Depth"))
        self.checkBox_6.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_5.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_4.setText(_translate("Dialog", "CheckBox"))
        self.b_run.setToolTip(_translate("Dialog", "Start the calculation"))
        self.b_run.setText(_translate("Dialog", "Run"))
