# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1406, 785)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(470, 630, 325, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.c_speed_plot = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_speed_plot.setFont(font)
        self.c_speed_plot.setObjectName("c_speed_plot")
        self.horizontalLayout_4.addWidget(self.c_speed_plot)
        self.c_error_plot = QtWidgets.QCheckBox(self.layoutWidget)
        self.c_error_plot.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_error_plot.setFont(font)
        self.c_error_plot.setObjectName("c_error_plot")
        self.horizontalLayout_4.addWidget(self.c_error_plot)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(810, 10, 444, 280))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.t_fps = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.t_fps.setFont(font)
        self.t_fps.setAlignment(QtCore.Qt.AlignCenter)
        self.t_fps.setObjectName("t_fps")
        self.horizontalLayout_3.addWidget(self.t_fps)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.c_of = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_of.setFont(font)
        self.c_of.setObjectName("c_of")
        self.verticalLayout_2.addWidget(self.c_of)
        self.c_back_of = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_back_of.setFont(font)
        self.c_back_of.setObjectName("c_back_of")
        self.verticalLayout_2.addWidget(self.c_back_of)
        self.c_depth = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_depth.setFont(font)
        self.c_depth.setObjectName("c_depth")
        self.verticalLayout_2.addWidget(self.c_depth)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.c_error_plot_video = QtWidgets.QCheckBox(self.layoutWidget1)
        self.c_error_plot_video.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_error_plot_video.setFont(font)
        self.c_error_plot_video.setObjectName("c_error_plot_video")
        self.verticalLayout_4.addWidget(self.c_error_plot_video)
        self.c_speed_plot_video = QtWidgets.QCheckBox(self.layoutWidget1)
        self.c_speed_plot_video.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_speed_plot_video.setFont(font)
        self.c_speed_plot_video.setObjectName("c_speed_plot_video")
        self.verticalLayout_4.addWidget(self.c_speed_plot_video)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_4.addWidget(self.checkBox_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(260, 500, 759, 100))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.combo_superpixel = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.combo_superpixel.setFont(font)
        self.combo_superpixel.setObjectName("combo_superpixel")
        self.combo_superpixel.addItem("")
        self.combo_superpixel.addItem("")
        self.combo_superpixel.addItem("")
        self.combo_superpixel.addItem("")
        self.combo_superpixel.addItem("")
        self.verticalLayout_8.addWidget(self.combo_superpixel)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 30, 300, 240))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b_save = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_save.sizePolicy().hasHeightForWidth())
        self.b_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_save.setFont(font)
        self.b_save.setObjectName("b_save")
        self.horizontalLayout_2.addWidget(self.b_save)
        self.l_save = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_save.setFont(font)
        self.l_save.setToolTip("")
        self.l_save.setText("")
        self.l_save.setObjectName("l_save")
        self.horizontalLayout_2.addWidget(self.l_save)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_vid = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_vid.sizePolicy().hasHeightForWidth())
        self.b_vid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_vid.setFont(font)
        self.b_vid.setObjectName("b_vid")
        self.horizontalLayout.addWidget(self.b_vid)
        self.l_vid = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_vid.setFont(font)
        self.l_vid.setText("")
        self.l_vid.setObjectName("l_vid")
        self.horizontalLayout.addWidget(self.l_vid)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.b_ground_truth = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_ground_truth.sizePolicy().hasHeightForWidth())
        self.b_ground_truth.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_ground_truth.setFont(font)
        self.b_ground_truth.setObjectName("b_ground_truth")
        self.horizontalLayout_9.addWidget(self.b_ground_truth)
        self.l_ground_truth = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_ground_truth.setFont(font)
        self.l_ground_truth.setText("")
        self.l_ground_truth.setObjectName("l_ground_truth")
        self.horizontalLayout_9.addWidget(self.l_ground_truth)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.layoutWidget4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(340, 240, 408, 162))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.t_fps_2 = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.t_fps_2.setFont(font)
        self.t_fps_2.setAlignment(QtCore.Qt.AlignCenter)
        self.t_fps_2.setObjectName("t_fps_2")
        self.horizontalLayout_5.addWidget(self.t_fps_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.t_fps_3 = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.t_fps_3.setFont(font)
        self.t_fps_3.setAlignment(QtCore.Qt.AlignCenter)
        self.t_fps_3.setObjectName("t_fps_3")
        self.horizontalLayout_8.addWidget(self.t_fps_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.layoutWidget5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget5.setGeometry(QtCore.QRect(960, 350, 408, 120))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.c_depth_2 = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.c_depth_2.setFont(font)
        self.c_depth_2.setObjectName("c_depth_2")
        self.verticalLayout_12.addWidget(self.c_depth_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.b_colour = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_colour.sizePolicy().hasHeightForWidth())
        self.b_colour.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_colour.setFont(font)
        self.b_colour.setObjectName("b_colour")
        self.horizontalLayout_7.addWidget(self.b_colour)
        self.l_colour = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_colour.setFont(font)
        self.l_colour.setText("")
        self.l_colour.setObjectName("l_colour")
        self.horizontalLayout_7.addWidget(self.l_colour)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 370, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_v = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_v.setContentsMargins(0, 0, 0, 0)
        self.layout_v.setObjectName("layout_v")
        self.b_run = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_run.sizePolicy().hasHeightForWidth())
        self.b_run.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_run.setFont(font)
        self.b_run.setObjectName("b_run")
        self.layout_v.addWidget(self.b_run)

        self.retranslateUi(Dialog)
        self.combo_superpixel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setToolTip(_translate("Dialog", "Select the plots you wish to create"))
        self.label_3.setText(_translate("Dialog", "Create Plot"))
        self.c_speed_plot.setText(_translate("Dialog", "Speed Plot"))
        self.c_error_plot.setText(_translate("Dialog", "Error Plot"))
        self.label.setToolTip(_translate("Dialog", "Select the videos you wish to create"))
        self.label.setText(_translate("Dialog", "Create Video"))
        self.label_2.setText(_translate("Dialog", "Fps"))
        self.t_fps.setToolTip(_translate("Dialog", "The fps for the created videos"))
        self.t_fps.setText(_translate("Dialog", "30"))
        self.c_of.setToolTip(_translate("Dialog", "Video of optical flow"))
        self.c_of.setText(_translate("Dialog", "Optical Flow"))
        self.c_back_of.setToolTip(_translate("Dialog", "Video of backward optical flow"))
        self.c_back_of.setText(_translate("Dialog", "Back Optical Flow"))
        self.c_depth.setToolTip(_translate("Dialog", "Video of depth estimation"))
        self.c_depth.setText(_translate("Dialog", "Depth"))
        self.c_error_plot_video.setText(_translate("Dialog", "Error Plot"))
        self.c_speed_plot_video.setText(_translate("Dialog", "Speed Plot"))
        self.checkBox_4.setText(_translate("Dialog", "CheckBox"))
        self.label_4.setToolTip(_translate("Dialog", "Select the plots you wish to create"))
        self.label_4.setText(_translate("Dialog", "Superpixel segmentation"))
        self.combo_superpixel.setItemText(0, _translate("Dialog", "Nothing"))
        self.combo_superpixel.setItemText(1, _translate("Dialog", "Felzenszwalb’s efficient graph based segmentation"))
        self.combo_superpixel.setItemText(2, _translate("Dialog", "Quickshift image segmentation"))
        self.combo_superpixel.setItemText(3, _translate("Dialog", "SLIC - K-Means based image segmentation"))
        self.combo_superpixel.setItemText(4, _translate("Dialog", "Compact watershed segmentation of gradient images"))
        self.label_5.setToolTip(_translate("Dialog", "Select the plots you wish to create"))
        self.label_5.setText(_translate("Dialog", "Data Save/Load"))
        self.b_save.setToolTip(_translate("Dialog", "Save path for results"))
        self.b_save.setText(_translate("Dialog", "Save Path"))
        self.b_vid.setToolTip(_translate("Dialog", "Video you wish to analyse"))
        self.b_vid.setText(_translate("Dialog", "Open Video"))
        self.b_ground_truth.setToolTip(_translate("Dialog", "Video you wish to analyse"))
        self.b_ground_truth.setText(_translate("Dialog", "Load Ground Truth"))
        self.label_6.setToolTip(_translate("Dialog", "Select the plots you wish to create"))
        self.label_6.setText(_translate("Dialog", "Parameters"))
        self.label_7.setText(_translate("Dialog", "Low Cut"))
        self.t_fps_2.setToolTip(_translate("Dialog", "The fps for the created videos"))
        self.t_fps_2.setText(_translate("Dialog", "30"))
        self.label_8.setText(_translate("Dialog", "High Cut"))
        self.t_fps_3.setToolTip(_translate("Dialog", "The fps for the created videos"))
        self.t_fps_3.setText(_translate("Dialog", "30"))
        self.c_depth_2.setToolTip(_translate("Dialog", "Video of depth estimation"))
        self.c_depth_2.setText(_translate("Dialog", "Create CSV from Speed data"))
        self.b_colour.setToolTip(_translate("Dialog", "Filling colour around the video"))
        self.b_colour.setText(_translate("Dialog", "Image Fill Colour"))
        self.b_run.setToolTip(_translate("Dialog", "Start the calculation"))
        self.b_run.setText(_translate("Dialog", "Run"))
