# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.layout_vid = QtWidgets.QVBoxLayout(self.widget)
        self.layout_vid.setContentsMargins(0, 0, 0, 0)
        self.layout_vid.setObjectName("layout_vid")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_video_left = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_video_left.sizePolicy().hasHeightForWidth())
        self.b_video_left.setSizePolicy(sizePolicy)
        self.b_video_left.setObjectName("b_video_left")
        self.horizontalLayout_3.addWidget(self.b_video_left)
        self.b_video_up = QtWidgets.QPushButton(self.widget)
        self.b_video_up.setObjectName("b_video_up")
        self.horizontalLayout_3.addWidget(self.b_video_up)
        self.b_video_right = QtWidgets.QPushButton(self.widget)
        self.b_video_right.setObjectName("b_video_right")
        self.horizontalLayout_3.addWidget(self.b_video_right)
        self.layout_vid.addLayout(self.horizontalLayout_3)
        self.l_description = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_description.setFont(font)
        self.l_description.setAlignment(QtCore.Qt.AlignCenter)
        self.l_description.setObjectName("l_description")
        self.layout_vid.addWidget(self.l_description)
        self.b_video_down = QtWidgets.QPushButton(self.widget)
        self.b_video_down.setObjectName("b_video_down")
        self.layout_vid.addWidget(self.b_video_down)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.layout_plot = QtWidgets.QVBoxLayout()
        self.layout_plot.setObjectName("layout_plot")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_plot_left = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_plot_left.sizePolicy().hasHeightForWidth())
        self.b_plot_left.setSizePolicy(sizePolicy)
        self.b_plot_left.setObjectName("b_plot_left")
        self.horizontalLayout.addWidget(self.b_plot_left)
        self.b_plot_right = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_plot_right.sizePolicy().hasHeightForWidth())
        self.b_plot_right.setSizePolicy(sizePolicy)
        self.b_plot_right.setObjectName("b_plot_right")
        self.horizontalLayout.addWidget(self.b_plot_right)
        self.layout_plot.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.layout_plot)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_fps = QtWidgets.QLabel(self.widget1)
        self.l_fps.setObjectName("l_fps")
        self.horizontalLayout_2.addWidget(self.l_fps)
        self.t_fps = QtWidgets.QLineEdit(self.widget1)
        self.t_fps.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t_fps.setAlignment(QtCore.Qt.AlignCenter)
        self.t_fps.setObjectName("t_fps")
        self.horizontalLayout_2.addWidget(self.t_fps)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_jump = QtWidgets.QPushButton(self.widget1)
        self.b_jump.setObjectName("b_jump")
        self.horizontalLayout_4.addWidget(self.b_jump)
        self.t_frame = QtWidgets.QLineEdit(self.widget1)
        self.t_frame.setInputMask("")
        self.t_frame.setObjectName("t_frame")
        self.horizontalLayout_4.addWidget(self.t_frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.b_rerun = QtWidgets.QPushButton(self.widget1)
        self.b_rerun.setObjectName("b_rerun")
        self.verticalLayout_4.addWidget(self.b_rerun)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 36))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolTip("")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionOF = QtWidgets.QAction(MainWindow)
        self.actionOF.setObjectName("actionOF")
        self.actionDepth = QtWidgets.QAction(MainWindow)
        self.actionDepth.setObjectName("actionDepth")
        self.actionNew_Run = QtWidgets.QAction(MainWindow)
        self.actionNew_Run.setObjectName("actionNew_Run")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew_Run)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.actionOF)
        self.toolBar.addAction(self.actionDepth)

        self.retranslateUi(MainWindow)
        self.actionNew_Run.triggered.connect(self.b_rerun.click)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_video_left.setToolTip(_translate("MainWindow", "Jump to the previous frame"))
        self.b_video_left.setText(_translate("MainWindow", "PushButton"))
        self.b_video_up.setToolTip(_translate("MainWindow", "Change the selected video"))
        self.b_video_up.setText(_translate("MainWindow", "PushButton"))
        self.b_video_right.setToolTip(_translate("MainWindow", "Jump to the next frame"))
        self.b_video_right.setText(_translate("MainWindow", "PushButton"))
        self.l_description.setToolTip(_translate("MainWindow", "Description of the currently selected video"))
        self.l_description.setText(_translate("MainWindow", "TextLabel"))
        self.b_video_down.setToolTip(_translate("MainWindow", "Change Video"))
        self.b_video_down.setText(_translate("MainWindow", "PushButton"))
        self.b_plot_left.setToolTip(_translate("MainWindow", "Change plot"))
        self.b_plot_left.setText(_translate("MainWindow", "PushButton"))
        self.b_plot_right.setToolTip(_translate("MainWindow", "Change Plot"))
        self.b_plot_right.setText(_translate("MainWindow", "PushButton"))
        self.l_fps.setToolTip(_translate("MainWindow", "Frame rate per second"))
        self.l_fps.setText(_translate("MainWindow", "FPS:"))
        self.t_fps.setToolTip(_translate("MainWindow", "Select video frame rate per second"))
        self.t_fps.setText(_translate("MainWindow", "30"))
        self.b_jump.setToolTip(_translate("MainWindow", "Jumpt to the selected frame"))
        self.b_jump.setText(_translate("MainWindow", "Jump to Frame:"))
        self.t_frame.setToolTip(_translate("MainWindow", "Select the frame that you wish to jump to"))
        self.t_frame.setText(_translate("MainWindow", "0"))
        self.b_rerun.setToolTip(_translate("MainWindow", "Start a new run"))
        self.b_rerun.setText(_translate("MainWindow", "PushButton"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionPlay.setToolTip(_translate("MainWindow", "<html><head/><body><p>Play the selected video, or stop it.</p></body></html>"))
        self.actionPlay.setShortcut(_translate("MainWindow", "Space"))
        self.actionOF.setText(_translate("MainWindow", "OF"))
        self.actionOF.setToolTip(_translate("MainWindow", "Jump to optical flow video"))
        self.actionDepth.setText(_translate("MainWindow", "Depth"))
        self.actionDepth.setToolTip(_translate("MainWindow", "Jump to depth video"))
        self.actionNew_Run.setText(_translate("MainWindow", "New Run"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
