# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1189, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layout_vid = QtWidgets.QVBoxLayout()
        self.layout_vid.setObjectName("layout_vid")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_info = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.b_info.setObjectName("b_info")
        self.horizontalLayout_3.addWidget(self.b_info)
        self.b_video_left = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_video_left.sizePolicy().hasHeightForWidth())
        self.b_video_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(16)
        self.b_video_left.setFont(font)
        self.b_video_left.setObjectName("b_video_left")
        self.horizontalLayout_3.addWidget(self.b_video_left)
        self.b_video_up = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(16)
        self.b_video_up.setFont(font)
        self.b_video_up.setObjectName("b_video_up")
        self.horizontalLayout_3.addWidget(self.b_video_up)
        self.b_video_right = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(16)
        self.b_video_right.setFont(font)
        self.b_video_right.setObjectName("b_video_right")
        self.horizontalLayout_3.addWidget(self.b_video_right)
        self.layout_vid.addLayout(self.horizontalLayout_3)
        self.l_description = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_description.setFont(font)
        self.l_description.setText("")
        self.l_description.setAlignment(QtCore.Qt.AlignCenter)
        self.l_description.setObjectName("l_description")
        self.layout_vid.addWidget(self.l_description)
        self.b_video_down = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(16)
        self.b_video_down.setFont(font)
        self.b_video_down.setObjectName("b_video_down")
        self.layout_vid.addWidget(self.b_video_down)
        self.verticalLayout_5.addLayout(self.layout_vid)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.verticalLayoutWidget_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_plot = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.layout_plot.setContentsMargins(0, 0, 0, 0)
        self.layout_plot.setObjectName("layout_plot")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_plot_left = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_plot_left.sizePolicy().hasHeightForWidth())
        self.b_plot_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(16)
        self.b_plot_left.setFont(font)
        self.b_plot_left.setObjectName("b_plot_left")
        self.horizontalLayout.addWidget(self.b_plot_left)
        self.b_plot_right = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_plot_right.sizePolicy().hasHeightForWidth())
        self.b_plot_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(16)
        self.b_plot_right.setFont(font)
        self.b_plot_right.setObjectName("b_plot_right")
        self.horizontalLayout.addWidget(self.b_plot_right)
        self.layout_plot.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_fps = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(16)
        self.l_fps.setFont(font)
        self.l_fps.setObjectName("l_fps")
        self.horizontalLayout_2.addWidget(self.l_fps)
        self.t_fps = QtWidgets.QLineEdit(self.layoutWidget1)
        self.t_fps.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.t_fps.setAlignment(QtCore.Qt.AlignCenter)
        self.t_fps.setObjectName("t_fps")
        self.horizontalLayout_2.addWidget(self.t_fps)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_jump = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(16)
        self.b_jump.setFont(font)
        self.b_jump.setObjectName("b_jump")
        self.horizontalLayout_4.addWidget(self.b_jump)
        self.t_frame = QtWidgets.QLineEdit(self.layoutWidget1)
        self.t_frame.setInputMask("")
        self.t_frame.setObjectName("t_frame")
        self.horizontalLayout_4.addWidget(self.t_frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.b_rerun = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_rerun.setFont(font)
        self.b_rerun.setObjectName("b_rerun")
        self.verticalLayout_4.addWidget(self.b_rerun)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.splitter)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(11)
        self.toolBar.setFont(font)
        self.toolBar.setToolTip("")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionOF = QtWidgets.QAction(MainWindow)
        self.actionOF.setObjectName("actionOF")
        self.actionDepth = QtWidgets.QAction(MainWindow)
        self.actionDepth.setObjectName("actionDepth")
        self.actionNew_Run = QtWidgets.QAction(MainWindow)
        self.actionNew_Run.setObjectName("actionNew_Run")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOriginal = QtWidgets.QAction(MainWindow)
        self.actionOriginal.setObjectName("actionOriginal")
        self.actionBackOF = QtWidgets.QAction(MainWindow)
        self.actionBackOF.setObjectName("actionBackOF")
        self.actionOFDirections = QtWidgets.QAction(MainWindow)
        self.actionOFDirections.setObjectName("actionOFDirections")
        self.actionMask = QtWidgets.QAction(MainWindow)
        self.actionMask.setObjectName("actionMask")
        self.actionOFArrows = QtWidgets.QAction(MainWindow)
        self.actionOFArrows.setObjectName("actionOFArrows")
        self.actionSuperPixel = QtWidgets.QAction(MainWindow)
        self.actionSuperPixel.setObjectName("actionSuperPixel")
        self.actionShow_Log = QtWidgets.QAction(MainWindow)
        self.actionShow_Log.setObjectName("actionShow_Log")
        self.actionInformation = QtWidgets.QAction(MainWindow)
        self.actionInformation.setObjectName("actionInformation")
        self.actionObjectDetection = QtWidgets.QAction(MainWindow)
        self.actionObjectDetection.setObjectName("actionObjectDetection")
        self.menuFile.addAction(self.actionNew_Run)
        self.menuFile.addAction(self.actionInformation)
        self.menuFile.addAction(self.actionShow_Log)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.actionOriginal)
        self.toolBar.addAction(self.actionOF)
        self.toolBar.addAction(self.actionBackOF)
        self.toolBar.addAction(self.actionDepth)
        self.toolBar.addAction(self.actionMask)
        self.toolBar.addAction(self.actionObjectDetection)
        self.toolBar.addAction(self.actionOFArrows)
        self.toolBar.addAction(self.actionOFDirections)
        self.toolBar.addAction(self.actionSuperPixel)

        self.retranslateUi(MainWindow)
        self.actionNew_Run.triggered.connect(self.b_rerun.click)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_info.setText(_translate("MainWindow", "..."))
        self.b_video_left.setToolTip(_translate("MainWindow", "Jump to the previous frame"))
        self.b_video_left.setText(_translate("MainWindow", "Previous"))
        self.b_video_up.setToolTip(_translate("MainWindow", "Change the selected video"))
        self.b_video_up.setText(_translate("MainWindow", "Up"))
        self.b_video_right.setToolTip(_translate("MainWindow", "Jump to the next frame"))
        self.b_video_right.setText(_translate("MainWindow", "Next"))
        self.l_description.setToolTip(_translate("MainWindow", "Description of the currently selected video"))
        self.b_video_down.setToolTip(_translate("MainWindow", "Change Video"))
        self.b_video_down.setText(_translate("MainWindow", "Down"))
        self.b_plot_left.setToolTip(_translate("MainWindow", "Change plot"))
        self.b_plot_left.setText(_translate("MainWindow", "Previous"))
        self.b_plot_right.setToolTip(_translate("MainWindow", "Change plot"))
        self.b_plot_right.setText(_translate("MainWindow", "Next"))
        self.l_fps.setToolTip(_translate("MainWindow", "Frames per second"))
        self.l_fps.setText(_translate("MainWindow", "FPS:"))
        self.t_fps.setToolTip(_translate("MainWindow", "Select video frame rate per second"))
        self.t_fps.setText(_translate("MainWindow", "30"))
        self.b_jump.setToolTip(_translate("MainWindow", "Jumpt to the selected frame"))
        self.b_jump.setText(_translate("MainWindow", "Jump to Frame:"))
        self.t_frame.setToolTip(_translate("MainWindow", "Select the frame that you wish to jump to"))
        self.t_frame.setText(_translate("MainWindow", "0"))
        self.b_rerun.setToolTip(_translate("MainWindow", "Start a new run"))
        self.b_rerun.setText(_translate("MainWindow", "Run"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionPlay.setToolTip(_translate("MainWindow", "<html><head/><body><p>Play the selected video, or stop it.</p></body></html>"))
        self.actionPlay.setShortcut(_translate("MainWindow", "Space"))
        self.actionOF.setText(_translate("MainWindow", "OF"))
        self.actionOF.setToolTip(_translate("MainWindow", "Jump to optical flow video"))
        self.actionDepth.setText(_translate("MainWindow", "Depth"))
        self.actionDepth.setToolTip(_translate("MainWindow", "Jump to depth video"))
        self.actionNew_Run.setText(_translate("MainWindow", "New Run"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOriginal.setText(_translate("MainWindow", "Original"))
        self.actionOriginal.setToolTip(_translate("MainWindow", "Jump to original video"))
        self.actionBackOF.setText(_translate("MainWindow", "BackOF"))
        self.actionBackOF.setToolTip(_translate("MainWindow", "Jump to backward optical flow video"))
        self.actionOFDirections.setText(_translate("MainWindow", "OFDirections"))
        self.actionOFDirections.setToolTip(_translate("MainWindow", "Jump to optical flow directions video"))
        self.actionMask.setText(_translate("MainWindow", "Mask"))
        self.actionMask.setToolTip(_translate("MainWindow", "Jump to speed mask video"))
        self.actionOFArrows.setText(_translate("MainWindow", "OFArrows"))
        self.actionOFArrows.setToolTip(_translate("MainWindow", "Jump to optical flow arrows video"))
        self.actionSuperPixel.setText(_translate("MainWindow", "SuperPixel"))
        self.actionSuperPixel.setToolTip(_translate("MainWindow", "Jump to super pixel video"))
        self.actionShow_Log.setText(_translate("MainWindow", "Show Log"))
        self.actionInformation.setText(_translate("MainWindow", "Information"))
        self.actionObjectDetection.setText(_translate("MainWindow", "ObjectDetection"))
        self.actionObjectDetection.setToolTip(_translate("MainWindow", "Jump to object detection video"))
