# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(70, 30, 610, 462))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_video_left = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_video_left.sizePolicy().hasHeightForWidth())
        self.b_video_left.setSizePolicy(sizePolicy)
        self.b_video_left.setObjectName("b_video_left")
        self.horizontalLayout_3.addWidget(self.b_video_left)
        self.b_video_up = QtWidgets.QPushButton(self.layoutWidget)
        self.b_video_up.setObjectName("b_video_up")
        self.horizontalLayout_3.addWidget(self.b_video_up)
        self.b_video_right = QtWidgets.QPushButton(self.layoutWidget)
        self.b_video_right.setObjectName("b_video_right")
        self.horizontalLayout_3.addWidget(self.b_video_right)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.l_video = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_video.sizePolicy().hasHeightForWidth())
        self.l_video.setSizePolicy(sizePolicy)
        self.l_video.setObjectName("l_video")
        self.verticalLayout_5.addWidget(self.l_video)
        self.b_video_down = QtWidgets.QPushButton(self.layoutWidget)
        self.b_video_down.setObjectName("b_video_down")
        self.verticalLayout_5.addWidget(self.b_video_down)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_plot_left = QtWidgets.QPushButton(self.layoutWidget1)
        self.b_plot_left.setObjectName("b_plot_left")
        self.horizontalLayout.addWidget(self.b_plot_left)
        self.b_plot_right = QtWidgets.QPushButton(self.layoutWidget1)
        self.b_plot_right.setObjectName("b_plot_right")
        self.horizontalLayout.addWidget(self.b_plot_right)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.l_plot = QtWidgets.QLabel(self.layoutWidget1)
        self.l_plot.setObjectName("l_plot")
        self.verticalLayout_2.addWidget(self.l_plot)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hyperparamteres = QtWidgets.QListWidget(self.layoutWidget2)
        self.hyperparamteres.setObjectName("hyperparamteres")
        self.verticalLayout.addWidget(self.hyperparamteres)
        self.other = QtWidgets.QListWidget(self.layoutWidget2)
        self.other.setObjectName("other")
        self.verticalLayout.addWidget(self.other)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_video_left.setText(_translate("MainWindow", "PushButton"))
        self.b_video_up.setText(_translate("MainWindow", "PushButton"))
        self.b_video_right.setText(_translate("MainWindow", "PushButton"))
        self.l_video.setText(_translate("MainWindow", "TextLabel"))
        self.b_video_down.setText(_translate("MainWindow", "PushButton"))
        self.b_plot_left.setText(_translate("MainWindow", "PushButton"))
        self.b_plot_right.setText(_translate("MainWindow", "PushButton"))
        self.l_plot.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
