# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 406)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_v = QtWidgets.QVBoxLayout()
        self.layout_v.setObjectName("layout_v")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b_save = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_save.sizePolicy().hasHeightForWidth())
        self.b_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_save.setFont(font)
        self.b_save.setObjectName("b_save")
        self.horizontalLayout_2.addWidget(self.b_save)
        self.l_save = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_save.setFont(font)
        self.l_save.setToolTip("")
        self.l_save.setText("")
        self.l_save.setObjectName("l_save")
        self.horizontalLayout_2.addWidget(self.l_save)
        self.layout_v.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_of = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_of.sizePolicy().hasHeightForWidth())
        self.b_of.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_of.setFont(font)
        self.b_of.setObjectName("b_of")
        self.horizontalLayout_3.addWidget(self.b_of)
        self.l_of = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_of.setFont(font)
        self.l_of.setText("")
        self.l_of.setObjectName("l_of")
        self.horizontalLayout_3.addWidget(self.l_of)
        self.layout_v.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_depth = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_depth.sizePolicy().hasHeightForWidth())
        self.b_depth.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_depth.setFont(font)
        self.b_depth.setObjectName("b_depth")
        self.horizontalLayout_4.addWidget(self.b_depth)
        self.l_depth = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_depth.setFont(font)
        self.l_depth.setText("")
        self.l_depth.setObjectName("l_depth")
        self.horizontalLayout_4.addWidget(self.l_depth)
        self.layout_v.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.b_colour = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_colour.sizePolicy().hasHeightForWidth())
        self.b_colour.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_colour.setFont(font)
        self.b_colour.setObjectName("b_colour")
        self.horizontalLayout_5.addWidget(self.b_colour)
        self.l_colour = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_colour.setFont(font)
        self.l_colour.setText("")
        self.l_colour.setObjectName("l_colour")
        self.horizontalLayout_5.addWidget(self.l_colour)
        self.layout_v.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_vid = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_vid.sizePolicy().hasHeightForWidth())
        self.b_vid.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_vid.setFont(font)
        self.b_vid.setObjectName("b_vid")
        self.horizontalLayout.addWidget(self.b_vid)
        self.l_vid = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.l_vid.setFont(font)
        self.l_vid.setText("")
        self.l_vid.setObjectName("l_vid")
        self.horizontalLayout.addWidget(self.l_vid)
        self.layout_v.addLayout(self.horizontalLayout)
        self.b_run = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_run.sizePolicy().hasHeightForWidth())
        self.b_run.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("GE Inspira")
        font.setPointSize(20)
        self.b_run.setFont(font)
        self.b_run.setObjectName("b_run")
        self.layout_v.addWidget(self.b_run)
        self.verticalLayout_2.addLayout(self.layout_v)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.b_save.setToolTip(_translate("Dialog", "Save path for results"))
        self.b_save.setText(_translate("Dialog", "Save Path"))
        self.b_of.setToolTip(_translate("Dialog", "Optical flow running file"))
        self.b_of.setText(_translate("Dialog", "Optical flow"))
        self.b_depth.setToolTip(_translate("Dialog", "Depth estimation running file"))
        self.b_depth.setText(_translate("Dialog", "Depth"))
        self.b_colour.setToolTip(_translate("Dialog", "Filling colour around the video"))
        self.b_colour.setText(_translate("Dialog", "Image Fill Colour"))
        self.b_vid.setToolTip(_translate("Dialog", "Video you wish to analyse"))
        self.b_vid.setText(_translate("Dialog", "Open Video"))
        self.b_run.setToolTip(_translate("Dialog", "Start the calculation"))
        self.b_run.setText(_translate("Dialog", "Run"))
